---
- name: Install Fail2Ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Enable SSH security in Fail2Ban (jail.local)
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [sshd]
      enabled = true
      port = {{ ansible_port | default(22) }}
      logpath = ssh
      backend = systemd
      maxretry = 10
      bantime = 3600
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Enable Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
